### ISSUE TITLE
Provide precompiled binaries for Linux

### ISSUE THREAD

**Issue by probonopd** [CARTAvis/carta-archived#36]
Currently there seem to be no precompiled binaries for Linux which makes it unnecessarily hard to run Carta. Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed (unlike Snap and Flatpak)
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs (unlike Flatpak)
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

Please let me know if you are interested in providing an AppImage.

**Comment by grimmerk** [comment]
Thank you @probonopd , it looks an awesome tool. Does it include https://github.com/probonopd/linuxdeployqt ? Originally we plan to try `linuxdeployqt` since we used Qt Desktop framework.

**Comment by probonopd** [comment]
@grimmer0125 yes that is a good plan. `linuxdeployqt` can produce AppImages. It also has in its README some examples of projects that build AppImages using GitHub, Travis CI, and linuxdeployqt. Let me know if you run into issues.

**Comment by ajm-ska** [comment]
@probonopd We provided an AppImage option for our official CARTA 0.9 release e.g. https://github.com/CARTAvis/carta/releases/download/v0.9/CARTA-0.9r-ubuntu.AppImage Thanks.

**Comment by probonopd** [comment]
The desktop file is lacking a `Categories=` entry in the `*.desktop` file.

According to the [menu spec](https://standards.freedesktop.org/menu-spec/latest/apa.html),

> By including one of the Main Categories in an application's desktop entry file, the application will be ensured that it will show up in a section of the application menu dedicated to this category. If multiple Main Categories are included in a single desktop entry file, the entry may appear more than once in the menu. 

Hence, please add at least one of the following in the `Categories=` key.

Main Category | Description | Notes
-- | -- | --
AudioVideo | Application for presenting, creating, or processing multimedia (audio/video) |  
Audio | An audio application | Desktop entry must include AudioVideo as well
Video | A video application | Desktop entry must include AudioVideo as well
Development | An application for development |  
Education | Educational software |  
Game | A game |  
Graphics | Application for viewing, creating, or processing graphics |  
Network | Network application such as a web browser |  
Office | An office type application |  
Science | Scientific software |  
Settings | Settings applications | Entries may appear in a separate menu or as part of a 		"Control Center"
System | System application, "System Tools" such as say a log viewer or network monitor |  
Utility | Small utility application, "Accessories"

In addition, you could specify one or more from the longer list of [Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html).

Please test the result with `desktop-file-validate` and make sure it passes.

__electron-builder offers native support for this since [v19.22.1](https://github.com/electron-userland/electron-builder/releases/tag/v19.22.1).__. Please see the `category` key at https://www.electron.build/configuration/linux-other.

References: 
* https://github.com/AppImage/AppImageHub/issues/2
* https://travis-ci.org/AppImage/appimage.github.io/builds/292678578#L704

**Comment by ajm-ska** [comment]
@probonopd I made a new AppImage with a "Categories" entry in the "*.desktop" file. 
It is here: http://www.asiaa.sinica.edu.tw/~ajm/carta/appimage/CARTA-x86_64-ubuntu.AppImage

I was trying to follow the "How to submit AppImages to the catalog" instructions on https://github.com/AppImage/appimage.github.io in order to test it, but I can't seem to do it.
When I click the link it says: 
> Sorry, it looks like your fork is outdated!
> You’ll have to bring it up to date before you can propose changes.

Then when I click the "update your fork" button, it goes to a 404 Page Not found.

If I use the command line, switch to the CARTA branch, then try to push a file containing only the link, I get:
> remote: Permission to AppImage/appimage.github.io.git denied to ajm-asiaa.
> fatal: unable to access 'https://github.com/AppImage/appimage.github.io.git/': The requested URL > returned error: 403

Would you be able to test our updated AppImage please?

**Comment by probonopd** [comment]
Looks like the Key `Categories=` is not in the `*.desktop` file exactly once in https://github.com/CARTAvis/carta/releases/download/v0.9/CARTA-0.9r-el6-el7.AppImage

Test log:
https://travis-ci.org/AppImage/appimage.github.io/builds/302349945#L699

**Comment by probonopd** [comment]
With http://www.asiaa.sinica.edu.tw/%7Eajm/carta/appimage/CARTA-x86_64-ubuntu.AppImage I get another error:
https://travis-ci.org/AppImage/appimage.github.io/builds/302352921#L702

**Comment by ajm-asiaa** [comment]
I haven't added `Categories=` to the versions on Github yet.

As for the one with `AppRun: Permission denied`, could it be because my AppRun was actually just a renamed shell script? I took a look at several other AppImages on AppImageHub and their AppRun are symbolic links to their executable.

**Comment by ajm-ska** [comment]
@probonopd  I haven't added `Categories=` to the AppImage versions on Github yet.

As for the one with `AppRun: Permission denied`, could it be because my AppRun was actually just a renamed shell script? 

I took a look at several extracted AppImages on your AppImageHub and their AppRuns are symbolic links to their executable. We can't do it that way as we need the shell script to start our executable for a few reasons, one being to define the html page for the interface to load.

I put a new version here: http://www.asiaa.sinica.edu.tw/~ajm/carta/appimage/CARTA-x86_64.AppImage 
where AppRun is a symbolic link to our shell script `AppRun -> bin/carta.sh`. If you think that should work, could you test this new version please, or let me know if AppRun really needs to be a binary executable in order to pass the test?

**Comment by probonopd** [comment]
`AppRun` can be a symlink, an executable or a script. But it needs to have the permission bit set (`chmod +x AppRun`). In a test on my local machine, your latest AppImage worked in this regard.

**Comment by ajm-ska** [comment]
OK. Thank you for testing it.
