### ISSUE TITLE
Fix carta to use stoke[0] only for calculating percentile & quantile and render raster image, by default.

### ISSUE THREAD

**Issue by grimmerk** [CARTAvis/carta-archived#69]
The suggested testing items:

1. Need to test fits and casa image file, due to the axis order issue. #19 CAS-9784 fix for Loading CasaImage

2. Need to test if this pull request works after the permutation of fits file/casa image file. Since
a. original: (x, y, stoke, channel)
b. in some code (#19), we convert it to (x, y, channel, stoke) ?
c. after permutation, still need to choose stoke[0]

**Comment by confluence** [comment]
Yes, the problem here is the mixture of casa packages. I thought that the carta backend package dependencies were specific enough to force installation of the PPA version, but clearly not -- I will look into this.

I would very much like to make our packages compatible with KERN eventually -- unfortunately we are dependent on a particular version of CASA6, which is itself dependent on a particular version of casacore. That's why we build our own custom casacore + imageanalysis version. So right now these packages can't be installed in parallel. I recommend that you install carta inside a clean container.

**Comment by gijzelaerr** [comment]
updating the SO versions can cause trouble when people have your packages installed, upgrade their system or switch/install KERN release to a version that is bundled with a casacore with the same SO version but different ABI. It is a bit sad that the SO versioning is quite limited in protecting ABI compatibility issues, being single integer-based. A solution that could work is to name the libraries and packages in such a way that they don't conflict with the Debian/KERN casacore packages. That way they can happily live next to each other, without ever interfering with each other.

if the packages are compatible I'm more than happy to merge your work into KERN, obviously giving you credit on the required spots.
